export default [
    {
        path:'test',
        name:'test',
        icon:'el-icon-platform-eleme',
        meta:{
            label:'测试'
        },
        children:[
            {
                path:'test2',
                name:'test2',
                meta:{
                    label:'测试2'
                },
            }
        ]
    }
]
